apiVersion: v1
kind: Secret
metadata:
  name: notification-secret
stringData:
  GMAIL_ADDRESS: "harikrishna0521@gmail.com" #enter your email to get the id
  GMAIL_PASSWORD: "lydh oucp jjpd oshe"
type: Opaque

# Passw0rd@1234